
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/gk/anaconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.0-131-generic - x86_64
...
